In [2]:
# Importing key tools
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
# Importing data
depression_data = pd.read_csv("data/depression_data.csv")
depression_data.head()

,Name,Age,Marital Status,Education Level,Number of Children,Smoking Status,Physical Activity Level,Employment Status,Income,Alcohol Consumption,Dietary Habits,Sleep Patterns,History of Mental Illness,History of Substance Abuse,Family History of Depression,Chronic Medical Conditions
0,Christine Barker,31,Married,Bachelor's Degree,2,Non-smoker,Active,Unemployed,26265.67,Moderate,Moderate,Fair,Yes,No,Yes,Yes
1,Jacqueline Lewis,55,Married,High School,1,Non-smoker,Sedentary,Employed,42710.36,High,Unhealthy,Fair,Yes,No,No,Yes
2,Shannon Church,78,Widowed,Master's Degree,1,Non-smoker,Sedentary,Employed,125332.79,Low,Unhealthy,Good,No,No,Yes,No
3,Charles Jordan,58,Divorced,Master's Degree,3,Non-smoker,Moderate,Unemployed,9992.78,Moderate,Moderate,Poor,No,No,No,No
4,Michael Rich,18,Single,High School,0,Non-smoker,Sedentary,Unemployed,8595.08,Low,Moderate,Fair,Yes,No,Yes,Yes

In [4]:
# Checking for missing data
depression_data.isna().sum()

Name                            0
Age                             0
Marital Status                  0
Education Level                 0
Number of Children              0
Smoking Status                  0
Physical Activity Level         0
Employment Status               0
Income                          0
Alcohol Consumption             0
Dietary Habits                  0
Sleep Patterns                  0
History of Mental Illness       0
History of Substance Abuse      0
Family History of Depression    0
Chronic Medical Conditions      0
dtype: int64

In [10]:
# Finding data types
depression_data.dtypes

Name                             object
Age                               int64
Marital Status                   object
Education Level                  object
Number of Children                int64
Smoking Status                   object
Physical Activity Level          object
Employment Status                object
Income                          float64
Alcohol Consumption              object
Dietary Habits                   object
Sleep Patterns                   object
History of Mental Illness        object
History of Substance Abuse       object
Family History of Depression     object
Chronic Medical Conditions       object
dtype: object

In [14]:
# Seperating x and y variables
x = depression_data.drop("Income", axis=1)
y = depression_data["Income"]

# Dropping Name for ease of training
x = x.drop("Name", axis=1)

x.head()

,Age,Marital Status,Education Level,Number of Children,Smoking Status,Physical Activity Level,Employment Status,Alcohol Consumption,Dietary Habits,Sleep Patterns,History of Mental Illness,History of Substance Abuse,Family History of Depression,Chronic Medical Conditions
0,31,Married,Bachelor's Degree,2,Non-smoker,Active,Unemployed,Moderate,Moderate,Fair,Yes,No,Yes,Yes
1,55,Married,High School,1,Non-smoker,Sedentary,Employed,High,Unhealthy,Fair,Yes,No,No,Yes
2,78,Widowed,Master's Degree,1,Non-smoker,Sedentary,Employed,Low,Unhealthy,Good,No,No,Yes,No
3,58,Divorced,Master's Degree,3,Non-smoker,Moderate,Unemployed,Moderate,Moderate,Poor,No,No,No,No
4,18,Single,High School,0,Non-smoker,Sedentary,Unemployed,Low,Moderate,Fair,Yes,No,Yes,Yes

In [19]:
# Converting objects into numeric data with and then categorizing it
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Marital Status", "Education Level", "Smoking Status", "Physical Activity Level", 
                        "Employment Status", "Alcohol Consumption", "Dietary Habits", "Sleep Patterns",
                        "History of Mental Illness", "History of Substance Abuse", "Family History of Depression",
                        "Chronic Medical Conditions"]
one_hot = OneHotEncoder()
transformed_x = ColumnTransformer([("one_hot",
                                 one_hot,
                                 categorical_features)],
                                remainder="passthrough").fit_transform(x)
transformed_x

array([[ 0.,  1.,  0., ...,  1., 31.,  2.],
       [ 0.,  1.,  0., ...,  1., 55.,  1.],
       [ 0.,  0.,  0., ...,  0., 78.,  1.],
       ...,
       [ 0.,  1.,  0., ...,  1., 57.,  0.],
       [ 0.,  1.,  0., ...,  0., 71.,  2.],
       [ 0.,  0.,  0., ...,  0., 62.,  0.]], shape=(413768, 36))

In [27]:
# Trainging transformed_x with RandomForestRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, Y_test = train_test_split(transformed_x, y, test_size=0.2)
model = RandomForestRegressor()
model.fit(x_train, y_train)

RandomForestRegressor()

In [29]:
model.score(x_test, Y_test)

0.8817760852942842